export default  {
    products:[
        {
            _id: 1,
            name: 'Slim Chemise',
            category: 'Chemise',
            image:'/images/chemise.jpg',
            price:60,
            brand: 'Nike',
            rating:4.5,
            numReviews: 10,
            countInStock:5,
        },
        {
            _id: 2,
            name: 'Fit Shirt',
            category: 'Shirts',
            image:'/images/chemise.jpg',
            price:70,
            brand: 'Nike',
            rating:4.5,
            numReviews: 10,
            countInStock:6,
        
        },
        {
            _id: 3,
            name: 'Best Pants',
            category: 'Pants',
            image:'/images/chemise.jpg',
            price:50,
            brand: 'Nike',
            rating:4.5,
            numReviews: 8,
            countInStock:6,
        },
        {
            _id: 4,
            name: 'Best Pants',
            category: 'Pants',
            image:'/images/chemise.jpg',
            price:50,
            brand: 'Nike',
            rating:4.5,
            numReviews: 8,
            countInStock:6,
        },
        {
            _id: 5,
            name: 'Best Pants',
            category: 'Pants',
            image:'/images/chemise.jpg',
            price:50,
            brand: 'Nike',
            rating:4.5,
            numReviews: 8,
            countInStock:6,
        },
        {
            _id: 6,
            name: 'Best Pants',
            category: 'Pants',
            image:'/images/chemise.jpg',
            price:50,
            brand: 'Nike',
            rating:4.5,
            numReviews: 8,
            countInStock:6,
        },
    ]
}