export const CARTE_ADD_ITEM = "CARTE_ADD_ITEM";
export const CARTE_REMOVE_ITEM = "CARTE_REMOVE_ITEM";
export const CART_SAVE_SHIPPING = 'CART_SAVE_SHIPPING';
export const CART_SAVE_PAYMENT = 'CART_SAVE_PAYMENT'